#!/bin/bash

ARCH=("amd64" "arm64v8")
for arch in ${ARCH[@]}; do
  base="${arch}"
  if [[ "${arch}" == "amd64" ]]; then
    base="docker.io"
  fi

  echo "docker build . --build-arg ARCH=${base} -t ${DOCKER_REPO}:${arch}"
  docker build . --build-arg ARCH=${base} -t ${DOCKER_REPO}:${arch}
  echo "docker push ${DOCKER_REPO}:${arch}"
  docker push ${DOCKER_REPO}:${arch}
done
docker tag ${DOCKER_REPO}:amd64 ${DOCKER_REPO}:latest
